/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    FooterMusic: typeof import('./src/components/item/FooterMusic.vue')['default']
    Iconlist: typeof import('./src/components/Iconlist.vue')['default']
    IconList: typeof import('./src/components/IconList.vue')['default']
    ItemMusicList: typeof import('./src/components/item/ItemMusicList.vue')['default']
    ItemMusicTop: typeof import('./src/components/item/ItemMusicTop.vue')['default']
    MusicDetail: typeof import('./src/components/item/MusicDetail.vue')['default']
    MusicList: typeof import('./src/components/MusicList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SwpierTop: typeof import('./src/components/SwpierTop.vue')['default']
    TopNav: typeof import('./src/components/TopNav.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanPopup: typeof import('vant/es')['Popup']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
  }
}
